### ISSUE TITLE
How to add the bot?

### ISSUE THREAD

**Issue by Davi-the-Mudkip** [Benricheson101/discord-status#1]
How to add the bot? The readme doesn't show how to do it.

**Comment by Benricheson101** [comment]
[With commands](https://discord-status.red-panda.red) | [Without commands](https://discord.com/oauth2/authorize?client_id=662416455366737949&redirect_uri=https://discord-status.red-panda.red/auth/callback&response_type=code&scope=webhook.incoming)

**Comment by Davi-the-Mudkip** [comment]
> [With commands](https://discord-status.red-panda.red) | [Without commands](https://discord.com/oauth2/authorize?client_id=662416455366737949&redirect_uri=https://discord-status.red-panda.red/auth/callback&response_type=code&scope=webhook.incoming)

Those links should be on the readme.

**Comment by Benricheson101** [comment]
I can add them later
