### ISSUE TITLE
You already have a status page feed in your server.

### ISSUE THREAD

**Issue by acollierr17** [Benricheson101/discord-status#2]
Can you remove my guild from the database so I can use this interaction along with slash commands? The error I'm getting is down below and I no longer have the interaction or old webhook in my sever. The previous webhook I was using was from an old glitch app.

> You already have a status page feed in your server.

My guild ID: `601219766258106399`

**Comment by Benricheson101** [comment]
Deleted.

**Comment by acollierr17** [comment]
Thanks. Fixed.
