### ISSUE TITLE
Emoji not appearing

### ISSUE THREAD

**Issue by Davi-the-Mudkip** [Benricheson101/discord-status#3]
The emoji isn't appearing in the webhook's message, only the alias. How to fix that?

![image](https://user-images.githubusercontent.com/68123395/117554171-435ab600-b02c-11eb-8358-8313b8cff614.png)

**Comment by Benricheson101** [comment]
Give the @everyone role external emoji perms. Discord doesn't allow webhooks to use external emojis if that permission is denied.

**Comment by Davi-the-Mudkip** [comment]
Thanks.
