### ISSUE TITLE
You already have a status page feed in your server.

### ISSUE THREAD

**Issue by rparys** [Benricheson101/discord-status#5]
Hello there.
Cool project, I've been looking for a Discord status page bot for a while.

Unfortunately I first added the variant without commands and now I can't unsubscribe. I have already deleted the webhook integration. Still I can't add the version with commands anymore.

![11-06-2021_03-37-32](https://user-images.githubusercontent.com/24474449/121618416-0177c200-ca67-11eb-9642-0f15ce98057a.png)

My GuildID is `779849291966578718`

A small hint, if you use the version without commands, the command /unsubscribe does not work of course.
But it is still in the introduction message. If this is possible, you could change this in the version without commands.
![11-06-2021_03-44-48](https://user-images.githubusercontent.com/24474449/121618683-7e0aa080-ca67-11eb-92a4-c252c204f841.png)

Cheers.

**Comment by Benricheson101** [comment]
Sorry about that, try adding it now.
