### ISSUE TITLE
already have a status page feed in your server after deletion

### ISSUE THREAD

**Issue by auxtinn** [Benricheson101/discord-status#6]
i’m having the same issue as #5, except the status emojis stopped rendering so i tried deleting the integration and re-adding it and now it just keeps saying that i already have a status page feed in my server.

**Comment by Benricheson101** [comment]
Apologies for the late response. The emojis can be fixed by giving the `@everyone` role `Use External Emoji` perms

Try re-adding it now. It clears deleted servers every 24 hours.

**Comment by auxtinn** [comment]
> Apologies for the late response. The emojis can be fixed by giving the `@everyone` role `Use External Emoji` perms
> 
> 
> 
> Try re-adding it now. It clears deleted servers every 24 hours.

it's on but the emotes still don't show up..

**Comment by Benricheson101** [comment]
Check channel overrides. It will not retroactively update, but future updates will have working emojis.

To test if it is working, rub `/status summary`

If it continues to not work, it is likely a Discord bug.
